captcha/urls.py
from django.conf.urls import url
from captcha import views

urlpatterns = [
    url(r'image/(?P<key>\w+)/$', views.captcha_image, name='captcha-image', kwargs={'scale': 1}),
    url(r'image/(?P<key>\w+)@2/$', views.captcha_image, name='captcha-image-2x', kwargs={'scale': 2}),
    url(r'audio/(?P<key>\w+).wav$', views.captcha_audio, name='captcha-audio'),
    url(r'refresh/$', views.captcha_refresh, name='captcha-refresh'),
]

djangocms_charts/chartjs/urls.py
from __future__ import absolute_import, print_function, unicode_literals
from django.conf.urls import include, url
from djangocms_charts.chartjs.views.test_data_views import *
from djangocms_charts.chartjs.views.data_views import get_chartjs_json

urlpatterns = [

       # ChartJS JSON TEST Data Views
       # --------------------------------
       # Line chart
       url(r'^json/line-test/$', chartjs_line_json_view, name='chartjs_line_json_test'),
       # Bar chart
       url(r'^json/bar-test/$', chartjs_bar_json_view, name='chartjs_bar_json_test'),
       # Radar chart
       url(r'^json/radar-test/$', chartjs_radar_json_view, name='chartjs_radar_json_test'),
       # Polar Area chart
       url(r'^json/polar-test/$', chartjs_polar_json_view, name='chartjs_polar_json_test'),
       # Pie chart
       url(r'^json/pie-test/$', chartjs_pie_json_view, name='chartjs_pie_json_test'),
       # Doughnut chart
       url(r'^json/doughnut-test/$', chartjs_doughnut_json_view, name='chartjsdoughnut_json_test'),

       # ChartJS JSON Data Views
       # --------------------------------
       # Direct query to charts json values [chartjsmodel_id]
       url(r'^json/(?P<chartjsmodel_id>[0-9]+)/$', get_chartjs_json, name='chartjs_json'),

]

djangocms_charts/highcharts/urls.py
from __future__ import absolute_import, print_function, unicode_literals
from django.conf.urls import include, url


urlpatterns= [
        # # ChartJS JSON Data Views
        # # --------------------------------
        # # Line chart
        # url(r'^line/json/$', 'djangocms_charts.chartjs.views.views.chartjs_line_json', name='chartjs_line_json'),
        # # Bar chart
        # url(r'^bar/json/$', 'djangocms_charts.chartjs.views.views.chartjs_bar_json', name='chartjs_bar_json'),
        # # Radar chart
        # url(r'^radar/json/$', 'djangocms_charts.chartjs.views.views.chartjs_radar_json', name='chartjs_radar_json'),
        # # Polar chart
        # url(r'^polar/json/$', 'djangocms_charts.chartjs.views.views.chartjs_polar_json', name='chartjs_polar_json'),
        # # Pie chart
        # url(r'^pie/json/$', 'djangocms_charts.chartjs.views.views.chartjs_pie_json', name='chartjs_pie_json'),
        #
        # # ChartJS JSON TEST Data Views
        # # --------------------------------
        # # Line chart
        # url(r'^line/json/test/$', 'djangocms_charts.chartjs.views.test_views.chartjs_line_json', name='chartjs_line_json'),
        # # Bar chart
        # url(r'^bar/json/test/$', 'djangocms_charts.chartjs.views.test_views.chartjs_bar_json', name='chartjs_bar_json'),
        # # Radar chart
        # url(r'^radar/json/test/$', 'djangocms_charts.chartjs.views.test_views.chartjs_radar_json', name='chartjs_radar_json'),
        # # Polar chart
        # url(r'^polar/json/test/$', 'djangocms_charts.chartjs.views.test_views.chartjs_polar_json', name='chartjs_polar_json'),
        # # Pie chart
        # url(r'^pie/json/test/$', 'djangocms_charts.chartjs.views.test_views.chartjs_pie_json', name='chartjs_pie_json'),
]

djangocms_charts/urls.py

from __future__ import absolute_import, print_function, unicode_literals
from django.conf.urls import include, url

# Not used... need parent url (e.g. 'chartjs/') in app.urls

urlpatterns = [
    url(r'^chartjs/', include('djangocms_charts.chartjs.urls')),
    url(r'^highcharts/', include('djangocms_charts.highcharts.urls')),
]



djangocms_charts/base/models.py
import re
from django.db import models
from django.utils.translation import ugettext_lazy as _
from cms.models import CMSPlugin
from .consts import *

def get_chart_class():
    return ChartsBaseModel.get_class_string()

class ChartsBaseModel(CMSPlugin):
    """
    Charts Model
    """
    name = models.CharField(_("Name"), max_length=256)
    chart_type = None

    # Table data
    table_data = models.TextField(_("Chart Table data"), blank=True)

    # Set Headers in Top and/or Left
    labels_top = models.BooleanField(_("Labels top row"), default=True, help_text="here is some help")
    labels_left = models.BooleanField(_("Labels left column"), default=True)
    data_series_format = models.CharField(_("Data series in Rows or Cols)"), max_length=10, default='rows')

    # Chart Parameters
    chart_width = models.IntegerField(_("Chart Width"), default=400)
    chart_height = models.IntegerField(_("Chart Height"), default=400)
    chart_position = models.CharField(_("Chart Position"), max_length=100, blank=True)

    # Legend
    title_display = models.BooleanField(_("Display Title"), default=True)
    legend_display = models.BooleanField(_("Display Legend"), default=True)
    legend_position = models.CharField(_("Legend Position"), max_length=100, blank=True)

    # Get chart class - defined by cls.chart_type e.g. line-chart
    @classmethod
    def get_class_string(cls):
        chart_type = cls.chart_type.lower() if cls.chart_type else ''
        return str('{0}-chart ').format(chart_type)

    # Classes for each chart object
    chart_container_classes = models.TextField(_("Additional classes for Chart Container"), blank=True, default=get_chart_class)
    chart_title_classes = models.TextField(_("Additional classes for Chart Title"), blank=True, default=get_chart_class)
    chart_classes = models.TextField(_("Additional classes for Chart"), blank=True, default=get_chart_class)
    legend_classes = models.TextField(_("Additional classes for Legend"), blank=True, default=get_chart_class)

    # Chart name
    def _chart_name(self):
        get_name = str("{0}_{1}").format(self.name,self.id).lower() # get name_id
        #  Replace all non-chars
        get_name = re.sub(r"[^\w\s]", '', get_name)
        # Replace all spaces with _
        get_name = re.sub(r"\s+", '_', get_name)
        return get_name

    # Chart Id
    def chart_id(self):
        get_chart_id = self.chart_type.lower() + '-chart_' + self._chart_name()
        return get_chart_id
    chart_id.short_description = 'Chart Id'

    # Chart Container Id
    def chart_container_id(self):
        return self.chart_type.lower() + '-chart-container_' + self._chart_name()
    chart_container_id.short_description = 'Chart Container Id'

    # Chart Title Id
    def chart_title_id(self):
        return self.chart_type.lower() + '-chart-title_' + self._chart_name()
    chart_title_id.short_description = 'Chart Title Id'

    # Legend Id
    def legend_id(self):
        return self.chart_type.lower() + '-chart-legend_' + self._chart_name()
    legend_id.short_description = 'Legend Id'

    def set_legend_width(self):
        return self.legend_position_in_top_bottom()

    def legend_position_in_top_bottom(self):
        top_bottom_positions = [LEGEND_POSITIONS.BOTTOM, LEGEND_POSITIONS.TOP]
        top_bottom_labels = [get_legend_class(pos) for pos in top_bottom_positions]
        return self.legend_position in top_bottom_labels


    # Chart Name
    def __unicode__(self):
        return self.name

    search_fields = ('name', 'table_data')

    class Meta:
        abstract = True



djangocms_charts/models.py

from cms.models import CMSPlugin

from .chartjs.models import *


djangocms_charts/chartjs/forms.py
from django import forms
from .consts import *
from .models import *
from djangocms_charts.base.forms import ChartsBaseInputForm
from djangocms_charts.widgets import *

class ChartJsInputForm(ChartsBaseInputForm):

    # Clean form and validate dependent fields
    def clean(self):
        cleaned_data = super(ChartJsInputForm, self).clean()

        # Check if either label has been selected
        top = cleaned_data['labels_top']
        left = cleaned_data['labels_left']
        data_series_in_rows = cleaned_data['data_series_format'] == 'rows'

        msg = "Data Labels are required (for x-axis)"

        if self.chart_type in CHART_TYPES.get_label_value_types :
            if not left and data_series_in_rows:
                self.add_error('labels_left', msg)
        else :
            if not top and data_series_in_rows :
                self.add_error('labels_top', msg)
            elif not left and not data_series_in_rows :
                self.add_error('labels_left', msg)


    class Meta:
        model = ChartJsBaseModel
        exclude = (
            'page',
            'position',
            'placeholder',
            'language',
            'plugin_type',
        )

djangocms_charts/base/views/chart_view.py
from .json_view import JSONView
import json
from djangocms_charts.utils import *
from six import string_types

class BaseChartView(JSONView):

    # Chart type to be defined when calling the base class
    chart_type = None
    data = None
    labels_top = None
    labels_left = None
    data_series_in_rows = None

    def get_chart_type(self):
        if self.chart_type == None:
            raise NotImplementedError(  # pragma: no cover
                'Chart type is not set, use class CHART_TYPE.LINE, ...BAR etc.')
        else:
            return self.chart_type

    # Main function to return JSON data - overwriting ContextMixin
    def __init__(self, chart_data_instance, **kwargs):

        super(BaseChartView, self).__init__(**kwargs)

        self.chart_type = chart_data_instance.chart_type
        self.data_series_in_rows = (chart_data_instance.data_series_format == 'rows')

        #If Table data is a string (as saved by django) then load it as array.
        table_data = json.loads(chart_data_instance.table_data) if isinstance(chart_data_instance.table_data, string_types) else chart_data_instance.table_data

        # Switch top/left if data is transposed
        if self.data_series_in_rows:
            self.labels_top = chart_data_instance.labels_top
            self.labels_left = chart_data_instance.labels_left
            self.data = table_data
        else :
            self.labels_top = chart_data_instance.labels_left
            self.labels_left = chart_data_instance.labels_top
            self.data = transpose(table_data)

    # Set the data start for rows
    def _row_start(self):
        row_start = 0
        if(self.labels_top) :
            row_start = 1
        return row_start

    # Set the data start for cols
    def _col_start(self):
        col_start = 0
        if(self.labels_left) :
            col_start = 1
        return col_start

    # Get the data excluding labels on top/left if set - convert all values to float!~
    def get_data(self):
        get_data = [list(map(float, self.data[i][self._col_start():])) for i in range(self._row_start(), len(self.data))]
        return get_data

    # Data is already transposed so Labels are always at the top
    def get_labels(self):
        # For columns of data with top row = x-axis label
        if(self.labels_top) :
            return self.data[0][self._col_start():]

        # For no data x-axis labels
        return None

    # Data is already transposed so Data Series Labels are always at the left
    def get_series_labels(self):
        # For rows of data with first col = series label
        if(self.labels_left) :
            return [self.data[i][0] for i in range(self._row_start(), len(self.data))]

        # For no data series labels
        return None

    #Chart Options to be specified for each instance
    def get_context_data(self):
        raise NotImplementedError(  # pragma: no cover
            'You should return context data - in the required format')

    #Chart Options to be specified for each instance
    def get_chart_options(self):
        raise NotImplementedError(  # pragma: no cover
            'You should return the options for this chart - in the required format')

    # Return the JSON string
    def get_json(self):
        return self.convert_context_to_json(self.get_context_data())

    #Return an HTTP view of the JSON data
    def get_json_view(self):
        return self.render_to_response(self.get_context_data())

    class Meta:
        abstract = True

djangocms_charts/base/views/json_view.py
# -*- coding: utf-8 -*-

#From ChartJs for Django

import json
from django import http
from django.views.generic import TemplateView


class ComplexEncoder(json.JSONEncoder):
    """Always return JSON primitive."""
    def default(self, obj):
        try:
            return super(ComplexEncoder, obj).default(obj)
        except TypeError:
            if hasattr(obj, 'pk'):
                return obj.pk
            return str(obj)


class JSONResponseMixin(object):
    def render_to_response(self, context):
        "Returns a JSON response containing 'context' as payload"
        return self.get_json_response(self.convert_context_to_json(context))

    def get_json_response(self, content, **httpresponse_kwargs):
        "Construct an `HttpResponse` object."
        return http.HttpResponse(content,
                                 content_type='application/json',
                                 **httpresponse_kwargs)

    def convert_context_to_json(self, context):
        "Convert the context dictionary into a JSON object"
        return json.dumps(context, cls=ComplexEncoder)


class JSONView(JSONResponseMixin, TemplateView):
    """A Base JSON View using the Mixin."""
    pass

djangocms_charts/chartjs/views/chart_views.py
from djangocms_charts.base.views.chart_view import BaseChartView
from djangocms_charts.chartjs.consts import *

class ChartJsView(BaseChartView):

    # Main function to return JSON data - overwriting ContextMixin
    # -------------------
    def get_context_data(self):

        # Return a data array with either a dataset, label/value pairs
        dataset_type = DATA_LABELS.VALUE if self.get_chart_type() in CHART_TYPES.get_label_value_types else DATA_LABELS.DATASET

        if dataset_type == DATA_LABELS.DATASET:
            data = self._build_dataset()
        else:
            data = self._build_data()

        return data

    # Build Dataset type values - Line, Bar, Radar etc
    # -------------------
    def _build_dataset(self):

        # Data array is the return object
        data = {}

        # Try to get the series data labels if present
        try:
            series_labels = self.get_series_labels()
        except:
            series_labels = None

        # Data is inserted into the Datasets
        datasets = []
        get_data = self.get_data()
        for i, the_data in enumerate(get_data):
            # Add Labels if present
            if series_labels :
                dataset = {DATA_LABELS.LABEL: series_labels[i],
                           DATA_LABELS.DATA: the_data}
            else:
                dataset = {DATA_LABELS.DATA: the_data}

            # Append to the dataset
            datasets.append(dataset)

        # Add Data and X-Axis Labels
        if self.get_labels() :
            data[DATA_LABELS.LABELS] = self.get_labels()
        data[DATA_LABELS.DATASET] = datasets

        return data


    # Build Data Array type values (Label, Values) - Pie, Polar etc
    # -------------------
    def _build_data(self):
        # Data array is the return object
        data = []

        # Try to get the series data labels if present, then labels if not
        try:
            series_labels = self.get_series_labels()
        except:
            try:
                series_labels = self.get_labels()
            except:
                series_labels = None

        # Data is inserted into each value/data pair
        get_data = self.get_data()

        for i, the_data in enumerate(get_data):
            # Add Labels if present
            if series_labels:
                dataset = {DATA_LABELS.LABEL: series_labels[i],
                           DATA_LABELS.VALUE: the_data[0]}
            else:
                dataset = {DATA_LABELS.VALUE: the_data[0]}

            # Append to data
            data.append(dataset)

        return data

    # class Meta:
    #     abstract = True

djangocms_charts/chartjs/views/data_views.py
# -*- coding: utf-8 -*-
"""Tools to build Line charts parameters."""
from django.shortcuts import get_object_or_404
from .chart_views import ChartJsView
from djangocms_charts.chartjs.models import ChartJsBaseModel

def get_chartjs_json(request, chartjsmodel_id):
    #Get Chart Data
    chart_data = get_object_or_404(ChartJsBaseModel, pk=chartjsmodel_id)
    chart_view = ChartJsView(chart_data)
    return chart_view.get_json_view()

djangocms_charts/templates/djangocms_charts/widgets/input-table.html
<div id="input-table"></div>

<script type="text/javascript">
    //<![CDATA]

    (function ($) {

        $(document).ready(function () {

            //Get data if exists
            //*******************************************
            var orig_data = null;
            {% if data %}
                orig_data = {{ data|safe }};
            {% endif %}
            var temp_data = orig_data;

            // Chart type sets the columns
            //*******************************************
            var chart_type = "{{ chart_type|safe }}";

            //Get Chart types and set headers, input table container etc.
            //*******************************************
            var LABEL_VALUE_CHART_TYPES = {{ LABEL_VALUE_CHART_TYPES|safe }};
            var container = document.getElementById("input-table");
            var input_table;

            //Set Rendering Functions for Labels or Values
            //*******************************************
            var labelRenderer = function (instance, td, row, col, prop, value, cellProperties) {
                Handsontable.TextCell.renderer.apply(this, arguments);
                td.style.background = '#EAEAEA';
                td.style.fontWeight = 'bold';
                td.style.textAlign = 'center';
            };

            var valueRenderer = function (instance, td, row, col, prop, value, cellProperties) {
                Handsontable.TextCell.renderer.apply(this, arguments);
                td.style.background = 'white !important';
                td.style.fontWeight = 'normal !important';
            };

            //Set Labels in top or left cols
            //*******************************************
            var labels_top = $("#id_labels_top").is(':checked');
            var labels_left = $("#id_labels_left").is(':checked');
            var data_series_select = $("#id_data_series_select").val();


            //Get the data as a two columns or full data
            //*******************************************
            function array_get_cols(the_data, num_cols) {
                if(!the_data) return;
                num_cols = num_cols ? num_cols : the_data[0].length;
                var x = the_data.map(function (the_row) {
                    return the_row.slice(0, num_cols);
                });
                return x;
            }


            //Output the table data on change or rebuild to the django div for save/loading.
            //*******************************************
            function get_table_data(){
                if (input_table != undefined) {
                    var get_data = input_table.getData();
                    return get_data;
                }
                return orig_data;
            }
            function output_data_to_dom(){
                $("#id_{{ name }}").val(JSON.stringify(get_table_data()));
            }
            function get_data_from_dom(){
                var get_data = $("#id_{{ name }}").val();
                if(get_data) {
                    get_data = JSON.parse(get_data);
                    return get_data;
                }
                return orig_data;
            }

            //Get Header Labels in First Row and/or First Column
            //*******************************************
            //On change of Header Labels - update validation and render table
            $("#id_labels_top").change(function () {
                validate_and_render();
            });
            $("#id_labels_left").change(function () {
                validate_and_render();
            });


            // Build Default Settings
            //*******************************************
            var options = {

                //Common Settings
                // ---------------------------
                rowHeaders: true,
                colHeaders: true,
                contextMenu: false,
                startRows: 5,
                minRows: 1,
                minCols: 1,
                manualColumnResize: true,

                // On Change write the data to temp area as json
                // ---------------------------
                afterChange: function (change, source) {
                    temp_data = get_table_data();
                    output_data_to_dom();
                },
                afterRender: function () {
                    temp_data = get_table_data();
                    output_data_to_dom();
                },

                //Format each cell based on label/value renderer
                // ---------------------------
                cells: function (row, col, prop) {

                    var cellProperties = {};

                    //If Label then set to grey background and text input
                    if ((row == 0 && $("#id_labels_top").is(':checked')) || (col == 0 && $("#id_labels_left").is(':checked'))) {
                        cellProperties = {
                            type: 'text',
                            renderer: labelRenderer,
                            validator: undefined //must be set explicitly as handsontable isn't working!
                        };
                        //If Input values then must be numeric for chart
                    } else {
                        cellProperties = {
                            type: 'numeric',
                            renderer: valueRenderer
                        };
                    }
                    return cellProperties;
                }
            };

            //Get the options based on Chart Type
            //*******************************************
            function set_options(chart_type) {

                // Label - Value Cols
                // ---------------------------
                if($.inArray(chart_type, LABEL_VALUE_CHART_TYPES) > -1) {

                    //Set the checkbox values
                    // ---------------------------
                    labels_top = $("#id_labels_top").is(':checked');
                    labels_left = $("#id_labels_left").is(':checked');
                    data_series_select= $("#id_data_series_select").val();

                    $("#id_labels_top").prop('checked', false);
                    $("#id_labels_left").prop('checked', true);
                    $("#id_data_series_select").val('Rows');

                    //Get data as a 2 column array only
                    // ---------------------------
                    options['data'] = array_get_cols(temp_data, 2);

                    // Set options for polar, pie, dougnut charts
                    // ---------------------------
                    options['colHeaders'] = ['Labels', 'Values'];
                    options['columns'] = [
                        {
                            // column options for the first column
                            type: 'text'
                        },
                        {
                            // column options for the second column
                            type: 'numeric'
                        }
                    ];
                    options['contextMenu'] = ['undo', 'redo', '---------', 'row_above', 'row_below', 'remove_row'];

                } else {

                // Data Series Cols
                // ---------------------------

                    //Set the checkbox values
                    // ---------------------------
                    $("#id_labels_top").prop('checked', labels_top);
                    $("#id_labels_left").prop('checked', labels_left);
                    $("#id_data_series_select").val(data_series_select);

                    //Get data as original loaded data
                    // ---------------------------
                    options['data'] = temp_data;

                    //Set options for all other types of charts
                    // ---------------------------
                    options['colHeaders'] = true;
                    options['columns'] = null;
                    options['startCols'] = 5;
                    options['contextMenu'] = ['undo', 'redo', '---------', 'row_above', 'row_below', 'remove_row', '---------', 'col_left', 'col_right', 'remove_col'];
                }

                //Common for all chart types
                // ---------------------------
                validate_and_render();

            }


            //Build Table
            //*******************************************
            build_table();

            function build_table() {
                set_options(chart_type);
                if (input_table != undefined && input_table.table != null) {
                    input_table.destroy();
                    input_table = undefined;
                }
                input_table = new Handsontable(container, options);
                output_data_to_dom();
                validate_and_render();
            }

            function validate_and_render() {
                if(input_table != undefined) {
                    input_table.validateCells();
                    input_table.render();
                }
            }

        });
    })(jQuery);


    //]]>
</script>
<style type="text/css">
    #id_{{ name }} {
        display: none !important;
    }
</style>